name: Publish PyPI release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  # Upload to PyPI
  pypi_upload:
    name: Push new release to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for setuptools-scm
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build and publish to PyPI
        env:
          # Username has to be __token__ to use API key
          TWINE_USERNAME: __token__
          # PyPI API key registered as an action secret for the repo
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m build
          twine check dist/*
          twine upload dist/*
