name: Format, Lint, and Test

on: [push]

jobs:
  format-lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install .["test"]
    - name: Format code with Black
      run: |
        black openmsitoolbox --check --diff
        black test --check --diff
    - name: Check code with pyflakes
      run: |
        pyflakes .
        cd test
        pyflakes .
    - name: Lint code with pylint
      run: |
        pylint openmsitoolbox
        pylint --recursive=y test
    - name: Run tests with unittest
      run: python -m unittest discover test
