name: Format, Lint, and Test

on: [push]

jobs:
  format-lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install .["test"]
    - name: Format code with Black
      run: |
        black openmsitoolbox --check
        black test --check
    - name: Check code with pyflakes
      run: |
        pyflakes .
        if [ $? -ne 0 ]; then
          echo "Pyflakes on openmsitoolbox failed!"
          exit 1
        fi
        cd test
        pyflakes .
        if [ $? -ne 0 ]; then
          echo "Pyflakes on tests failed!"
          exit 1
        fi
        cd ..
    - name: Lint code with pylint
      run: |
        pylint openmsitoolbox
        if [ $? -ne 0 ]; then
          echo "Pylint on openmsitoolbox failed!"
          exit 1
        fi
        pylint --recursive=y test
        if [ $? -ne 0 ]; then
          echo "Pylint on tests failed!"
          exit 1
        fi
    - name: Run tests with unittest
      run: python -m unittest discover test/test_scripts
