name: Format, Lint, and Test

on: [push]

jobs:
  format-lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.12']
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for setuptools-scm
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install .[test]
    - name: Format code with Black
      run: |
        black openmsitoolbox --check
        black test --check
    - name: Check code with pyflakes
      run: |
        pyflakes .
        cd test
        pyflakes .
        cd ..
    - name: Lint code with pylint
      run: |
        pylint openmsitoolbox --ignore version.py
        pylint --recursive=y test
    - name: Run tests with unittest
      run: python -m unittest discover test/test_scripts
